# Generated by Django 5.1.3 on 2024-11-18 09:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_route', models.CharField(max_length=64)),
                ('good_redirect_route', models.CharField(max_length=255)),
                ('bad_redirect_route', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SuspicousIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.CharField(max_length=64)),
                ('time_identified', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_allowed', models.DateTimeField(default=django.utils.timezone.now)),
                ('redirect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.requestredirect')),
            ],
        ),
        migrations.CreateModel(
            name='RequestSuspicousLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_route', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('suspicous_IP', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.suspicousip')),
            ],
        ),
    ]
