# Generated by Django 5.1.3 on 2024-11-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsuspicouslog',
            name='headers',
            field=models.TextField(blank=True),
        ),
    ]
