# Generated by Django 5.1.3 on 2024-11-18 16:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_requestsuspicouslog_headers'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestredirect',
            name='name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='requestredirect',
            name='short_description',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ip', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.requestredirect')),
            ],
        ),
    ]
