# Generated by Django 5.1.3 on 2024-11-19 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_requestredirect_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestlog',
            name='destination',
        ),
        migrations.AddField(
            model_name='requestlog',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='headers',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='method',
            field=models.CharField(blank=True, choices=[('GET', 'GET'), ('POST', 'POST')], max_length=10),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='redirect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.requestredirect'),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='request_type',
            field=models.CharField(blank=True, choices=[('GOOD', 'GOOD'), ('BAD', 'BAD')], max_length=10),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='source_ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.suspicousip'),
        ),
        migrations.DeleteModel(
            name='RequestSuspicousLog',
        ),
    ]
