# Generated by Django 5.1.3 on 2024-11-19 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_requestlog_destination_requestlog_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='sus_ip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.suspicousip'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='source_ip',
            field=models.CharField(max_length=64),
        ),
    ]
