# Generated by Django 5.1.3 on 2024-11-19 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_requestlog_sus_ip_alter_requestlog_source_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='sus_ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.suspicousip'),
        ),
    ]
