# Generated by Django 5.1.3 on 2024-11-19 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_requestlog_sus_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='sus_ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request_logs', to='core.suspicousip'),
        ),
    ]
