# Generated by Django 5.1.3 on 2024-11-20 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_requestlog_sus_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspicousip',
            name='redirect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.requestredirect'),
        ),
    ]
