# Generated by Django 5.1.3 on 2024-11-20 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_suspicousip_redirect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='sus_ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_logs', to='core.suspicousip'),
        ),
        migrations.AlterField(
            model_name='suspicousip',
            name='redirect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.requestredirect'),
        ),
    ]
