# Generated by Django 5.1.3 on 2024-11-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_requestlog_sus_ip_alter_suspicousip_redirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='response_body',
            field=models.TextField(blank=True),
        ),
    ]
