# Generated by Django 5.1.3 on 2024-11-20 10:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_requestlog_response_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspicousip',
            name='first_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
