# Generated by Django 5.1.3 on 2024-11-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_requestlog_headers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='request_type',
            field=models.CharField(blank=True, choices=[('GOOD', 'GOOD'), ('BAD', 'BAD'), ('BAD_ENTRY', 'BAD_ENTRY')], max_length=10),
        ),
    ]
