# Generated by Django 5.1.3 on 2024-11-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_requestlog_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='response_staus_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
