# Generated by Django 5.1.3 on 2024-11-20 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_requestlog_response_staus_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestlog',
            old_name='response_staus_code',
            new_name='response_status_code',
        ),
    ]
