# Generated by Django 5.1.3 on 2024-11-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_response_staus_code_requestlog_response_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='request_type',
            field=models.CharField(blank=True, choices=[('GOOD', 'GOOD'), ('BAD', 'BAD'), ('BAD_ENTRY', 'BAD_ENTRY'), ('CHECK', 'CHECK')], max_length=10),
        ),
    ]
